/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FareEstimateRouteImport } from './routes/fare-estimate'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RoutesSlugRouteImport } from './routes/routes.$slug'
import { Route as AuthenticatedAdminAdsLabelsRouteImport } from './routes/_authenticated/admin.ads-labels'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FareEstimateRoute = FareEstimateRouteImport.update({
  id: '/fare-estimate',
  path: '/fare-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/routes/$slug',
  path: '/routes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdsLabelsRoute =
  AuthenticatedAdminAdsLabelsRouteImport.update({
    id: '/admin/ads-labels',
    path: '/admin/ads-labels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/fare-estimate': typeof FareEstimateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/routes/': typeof RoutesIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ads-labels': typeof AuthenticatedAdminAdsLabelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/fare-estimate': typeof FareEstimateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/routes': typeof RoutesIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ads-labels': typeof AuthenticatedAdminAdsLabelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/fare-estimate': typeof FareEstimateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/routes/': typeof RoutesIndexRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/ads-labels': typeof AuthenticatedAdminAdsLabelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/fare-estimate'
    | '/sitemap.xml'
    | '/routes/$slug'
    | '/services/$slug'
    | '/routes/'
    | '/admin/access'
    | '/admin/ads-labels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/fare-estimate'
    | '/sitemap.xml'
    | '/routes/$slug'
    | '/services/$slug'
    | '/routes'
    | '/admin/access'
    | '/admin/ads-labels'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/fare-estimate'
    | '/sitemap.xml'
    | '/routes/$slug'
    | '/services/$slug'
    | '/routes/'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/ads-labels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  FareEstimateRoute: typeof FareEstimateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RoutesSlugRoute: typeof RoutesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fare-estimate': {
      id: '/fare-estimate'
      path: '/fare-estimate'
      fullPath: '/fare-estimate'
      preLoaderRoute: typeof FareEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/ads-labels': {
      id: '/_authenticated/admin/ads-labels'
      path: '/admin/ads-labels'
      fullPath: '/admin/ads-labels'
      preLoaderRoute: typeof AuthenticatedAdminAdsLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAdsLabelsRoute: typeof AuthenticatedAdminAdsLabelsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAdsLabelsRoute: AuthenticatedAdminAdsLabelsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  FareEstimateRoute: FareEstimateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RoutesSlugRoute: RoutesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
